### ISSUE TITLE
cosmétique

### ISSUE THREAD

**Issue by brol** [franck-paul/smiliesEditor#2]
salut,
la cosmétique dans les pages admin.php et index.php ne sont pas conforme à la charte graphique de dc2.6, dito pour les messages sur fond gris qui cachent le bouton d'aide. idem dans la page utilisateur, ce qui fait d'ailleurs planter la page à l'enregistrement.

**Comment by franck-paul** [comment]
Je sais il y a beaucoup à faire, mais pas le temps pour l'instant, j'ai juste fait le minimum pour que ça fonctionne.
